-- NOTE: `drizzle-kit generate` produced a much larger diff here (re-creating
-- company_memberships/reviews/subscriptions/subscription_invoices and
-- re-adding columns to booking_waitlist/clients) because migrations 0004 and
-- 0005 were hand-written and applied without ever running `drizzle-kit
-- generate` for them, so no snapshot was captured — drizzle's last real
-- snapshot was 0003, and it diffed schema.ts all the way from there. Every
-- one of those objects already exists in the database (verified directly via
-- psql) with a different-but-equivalent naming convention than what
-- drizzle-kit would generate. Re-running them would fail (duplicate index
-- names) or create confusing redundant constraints. This migration keeps only
-- the one statement that is genuinely new. The freshly generated
-- drizzle/meta/0006_snapshot.json is kept as-is (not pruned) — it correctly
-- captures schema.ts's real current state, which heals the drift for future
-- `drizzle-kit generate` diffs.
ALTER TABLE "bookings" ADD COLUMN "intended_payment_method" text;
